background #111111
foreground #dbdbdb

color8   #1b1d2b
color9   #b7374a
color10  #dbdbdb
color11  #dbdbdb
color12  #dbdbdb
color13  #dbdbdb
color14  #dbdbdb
color15  #dbdbdb

color0   #040511
color1   #db625e
color2   #dbdbdb
color3   #dbdbdb
color4   #dbdbdb
color5   #dbdbdb
color6   #333333
color7   #dbdbdb

shell fish

font_family      family="RobotoMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

window_padding_width 2 2
